# Generated by Django 2.2.2 on 2019-10-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Disease category')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='M_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Question')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('answer', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('d_title', models.ForeignKey(blank=True, null=True, on_delete='DO_NOTHING', to='products.D_category', verbose_name='Disease category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='m_title',
            field=models.ForeignKey(blank=True, null=True, on_delete='DO_NOTHING', to='products.M_category', verbose_name='Medicine Category'),
        ),
    ]
