# Generated by Django 2.2.6 on 2019-10-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191025_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_category',
            name='answer',
        ),
        migrations.AlterField(
            model_name='d_category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='m_category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='m_category',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Phase of Disease'),
        ),
    ]
